<?php  // $Id$

/**
 * @file
 * Provide scroll to top link.
 */

/**
 * Implementation of hook_init().
 */
function scroll_to_top_init() {
  if (!drupal_is_front_page()) {
    drupal_add_css(drupal_get_path('module', 'scroll_to_top') . '/scroll_to_top.css', 'module');
    drupal_add_js(drupal_get_path('module', 'scroll_to_top') . '/scroll_to_top.js');
  }
}

/**
 * Implementation of hook_node_view().
 */
function scroll_to_top_node_view($node, $view_mode, $langcode) {
  if (!drupal_is_front_page()) {

    $content='<p id="back-top">
	  <a href="#top"><span></span>Back to Top</a>
	</p>';
    $node->content['scroll'] = array(
        '#markup' => $content,
        '#weight' => 10,
    );
  }

}

